
pipeline:
  
    informStart:
        image: plugins/slack
        channel: ci
        template: |
          [{{ repo.name }}/{{ build.branch }} :: #{{ build.number }}]: Starting!


  
    buildTest:
        image: CHANGE
        commands:
          -npm install
          -./node_modules/lab/bin/lab -a code -t 100 --lint
        when:
          event: push

  
    dockerize:
        image: quay.io/golfnow/drone-docker
        privileged: true
        registry: quay.io
        repo: repository-name
        build_args: 
          -NPM_TOKEN={NPM_TOKEN}
        tags: 
          -1.0.0.${DRONE_BUILD_NUMBER}
        when:
          event: push


  
    deployProd:
        image: quay.io/golfnow/kube-deploy
        pull: true
        targets: 
          -repository-name-g1-customer
          -repository-name-g1-order-item
          -repository-name-g1-orders
          -repository-name-g1-res
        type: deployment
        tag: quay.io/golfnow/repository-name:1.0.0.${DRONE_BUILD_NUMBER}
        insecure: true
        useEnvironment: prd
        functions: 
          -annotate
        when:
          event: tag


  
    deployProd:
        image: quay.io/golfnow/kube-deploy
        pull: true
        targets: 
          -repository-name-g1-customer
          -repository-name-g1-order-item
          -repository-name-g1-orders
          -repository-name-g1-res
        type: deployment
        tag: quay.io/golfnow/repository-name:1.0.0.${DRONE_BUILD_NUMBER}
        insecure: true
        useEnvironment: prd
        functions: 
          -annotate
        when:
          event: tag


  
    informEnd:
        image: plugins/slack
        channel: ci
        template: |
          [{{ repo.name }}/{{ build.branch }} :: #{{ build.number }}]: {{ build.status }} after {{since build.started}}
        when:
          status: [ success, failure ]


